### PR TITLE
Added support for Windows Universal.

### PR DESCRIPTION
**Pull request by AmitBhatnagar24**
Added support for Windows Universal 
Added sample project.

### CODE REVIEW

**Comment by omuleanu** [comment]
what is the nuget folder for universal apps ?
for example atm all we have is  (lib/net40) :
https://github.com/omuleanu/ValueInjecter/tree/master/nuget/lib/net40

**Comment by AmitBhatnagar24** [comment]
Hrm.. I'm not too familar with how to construct nuget packages. Perhaps
this will help?

https://github.com/Windows-XAML/Template10/tree/master/Template10%20(Library)/Nuget

I use this UWP library lots and that's the nuget folder.

**Comment by omuleanu** [comment]
I've used lib/uap folder, you can try it now, the new package was published

**Comment by AmitBhatnagar24** [comment]
Thanks!

However when I try to build with the new nuget package, I get the following
error:

Error Could not copy the file
"C:\Users\ab.nuget\packages\valueinjecter\3.1.1.1\lib\uap\Omu.ValueInjecter\Properties\ValueInjecter_Universal.rd.xml"
because it was not found.

Any ideas?

**Comment by omuleanu** [comment]
there is no such file, 
you can see the files here: https://github.com/omuleanu/ValueInjecter/tree/master/nuget/lib/uap
and in your packages folder as well

**Comment by AmitBhatnagar24** [comment]
You need to modify nuget to include the following file in the deployment,
otherwise it won't work.

https://github.com/omuleanu/ValueInjecter/blob/master/ValueInjecter-Universal/Properties/ValueInjecter_Universal.rd.xml

Here are some options on how to do this:
http://dotnetbyexample.blogspot.ca/2015/12/fixing-file-rdxml-does-not-exist-when.html

looks like the easiest way would be to simply modify the buid action for
that file to be "Embedded Resource".

**Comment by omuleanu** [comment]
ok, try now

**Comment by AmitBhatnagar24** [comment]
Works now!

thanks!

**Comment by omuleanu** [comment]
You're Welcome !

**Pull request merged**
