### PR TITLE
Write to private setters in baseclasses

### PR DESCRIPTION
**Pull request by KeesDijk**
For a project we are working on we use ValueInjector and love it, thanks for your efforts.

In that project we have properties with private setters and everything worked fine until we moved one of these properties to a baseclass, valueinjector would not set the value anymore. Not sure if you want to call it a bug, in my mind at least it is incosistent behaviour. 

I my fork I added two unit test to show this behaviour and changed the SameNameType class with a possible solution, while keeping the original logic intact. 

I hope you will consider merging this fix or similar to ValueInjecter.

I needed to remove the signing from fork, probably would have been better not to commint these changes...

### CODE REVIEW

**Comment by omuleanu** [comment]
it is inconsistent indeed, 
but I think the default behaviour should not be affecting private properties/setters
so I think it would be correct if both your tests would fail

for your problem you could just create a separate injection and use that one instead of the default
`.InjectFrom<MyInj>(source)`

think I'll add the possibility to change the default injection (SameNameType), the same way you can change the default mapper now

**Comment by KeesDijk** [comment]
Thanks for the quick response.

Sounds like a plan, If there is a new injection that lets me inject into private setters, my problem is solved.

If you say that both my unittests should fail, that is not the way your code works at this time, this would create a breaking change, but that is up to you. I agree that the default behaviour should respect the private keyword and overriding this behaviour should be an opt-in.

If I can help in any way, just let me know.

**Comment by omuleanu** [comment]
the injection that lets you inject into private setters is the one that you created, just give it a different name and put it in your solution, and the problem is already solved for you

**Comment by KeesDijk** [comment]
Ah, okay, you will just add the possibility to change the default injection. The rest is up to me and anybody else who want's to override the default behaviour. Works for me, thank you.

**Comment by omuleanu** [comment]
yes, until this is added you can use `.InjectFrom<MyCustomInjection>(src)` instead of `.InjectFrom(src)`

**Comment by KeesDijk** [comment]
Okay

**Pull request closed without merging**
