### PR TITLE
fixes for universal project.

### PR DESCRIPTION
**Pull request by AmitBhatnagar24**
just a quick demonstration of what is required to get this to work with Universal apps. I didn't get a chance to run them thru the unit tests. I also removed the certificate to expedite me being able to build.

Not sure if this is best to be done in a portable class library.. ?

Hopefully this is enough to spark interest in an "official" supported Universal version of ValueInjecter.

### CODE REVIEW

**Comment by omuleanu** [comment]
could you please, create a very basic universal app in the Samples folder, and add a folder in the root for nuget as you need it to be
for the moment we have (not pushed)
nuget/lib/net45

**Comment by AmitBhatnagar24** [comment]
will this, or a similar update be made to support universal apps?

**Comment by omuleanu** [comment]
it needs to have some kind of test, like a basic demo app, plus you need to merge from master now

**Comment by AmitBhatnagar24** [comment]
I am unable to complete the tests and merge.

Will you be able to finish this? Has others requested a universal app version? Is there going to be continued development for ValueInjecter or should we move to auto mapper?

**Comment by omuleanu** [comment]
think it would be easier to fork again,
no need to copy the tests just create a demo app, like the ones present for windows forms,
I'm not familiar with universal apps, I tried to create basic app and I think it told me that I need a windows phone to run it,
nobody has requested this before
there will be development

**Comment by AmitBhatnagar24** [comment]
meet me in the gitter.im chat?

**Pull request closed without merging**
